import { NextResponse } from 'next/server';
import { z } from 'zod';
import { log, requireAdmin } from '@/lib/admin-api';
import { query } from '@/lib/database';
import { rangeFromRequest } from '@/lib/admin-date-range';
const input=z.object({company:z.string().min(1).max(200),country:z.string().max(80).optional(),industry:z.string().max(120).optional(),level:z.enum(['A','B','C','D']).default('C')});
export const runtime='nodejs';
export async function GET(request:Request){const b=await requireAdmin();if(b)return b;let range;try{range=rangeFromRequest(request)}catch{return NextResponse.json({error:'Invalid date range'},{status:400})}const url=new URL(request.url);const page=Math.max(1,Math.floor(Number(url.searchParams.get('page'))||1)),limit=20;const search=(url.searchParams.get('q')||'').trim().slice(0,120);const values:unknown[]=[range.start,range.end];let where='created_at >= $1 AND created_at < $2';if(search){values.push(`%${search}%`);where+=` AND (company ILIKE $${values.length} OR country ILIKE $${values.length})`;}const [rows,counts]=await Promise.all([query(`SELECT id,company,country,industry,level,updated_at FROM customers WHERE ${where} ORDER BY updated_at DESC LIMIT ${limit} OFFSET ${(page-1)*limit}`,values),query<{total:string;a_count:string;b_count:string}>(`SELECT count(*)::text total,count(*) FILTER(WHERE level='A')::text a_count,count(*) FILTER(WHERE level='B')::text b_count FROM customers WHERE ${where}`,values)]);const c=counts.rows[0];return NextResponse.json({rows:rows.rows,total:Number(c?.total||0),page,limit,summary:{total:Number(c?.total||0),a:Number(c?.a_count||0),b:Number(c?.b_count||0)}},{headers:{'Cache-Control':'private, no-store'}})}
export async function POST(request:Request){const b=await requireAdmin();if(b)return b;const p=input.safeParse(await request.json());if(!p.success)return NextResponse.json({error:'Invalid customer'},{status:400});const d=p.data;const r=await query<{id:string}>('INSERT INTO customers(company,country,industry,level) VALUES($1,$2,$3,$4) RETURNING id',[d.company,d.country||'',d.industry||'',d.level]);await log('created','customer',r.rows[0].id);return NextResponse.json(r.rows[0],{status:201})}
