'use client';

import Link from 'next/link';
import { useState } from 'react';
type Row = { label: string; value: string };
type Lead = { id: string; name: string; company: string; email: string; country: string; product: string; source: string; status: string; created_at: string };
type Data = { summary: { pv: string; visitors: string; sessions: string; inquiries: string }; trend: { date: string; pv: string; uv: string }[]; sources: Row[]; pages: Row[]; journeys: Row[]; recentLeads: Lead[]; range: number };
const number = (value: string) => Number(value || 0).toLocaleString();
function Bars({ title, rows, href }: { title: string; rows: Row[]; href?: string }) { const max = Math.max(...rows.map(r => Number(r.value)), 1); return <section className="admin-panel"><div className="admin-panel-heading"><h2>{title}</h2>{href ? <Link href={href}>查看详情</Link> : null}</div>{rows.length ? <div className="admin-bars">{rows.slice(0, 6).map(row => <div className="admin-bar" key={row.label}><span title={row.label}>{row.label}</span><i><b style={{ width: `${Math.max(4, Number(row.value) / max * 100)}%` }} /></i><strong>{number(row.value)}</strong></div>)}</div> : <p className="admin-empty">暂无真实访问记录</p>}</section>; }
function Trend({ rows }: { rows: Data['trend'] }) { const max = Math.max(...rows.map(row => Number(row.pv)), 1); return <section className="admin-panel admin-trend-panel"><div className="admin-panel-heading"><div><h2>访问趋势</h2><span>页面浏览量</span></div><Link href="/admin/analytics">流量分析</Link></div>{rows.length ? <div className="admin-chart">{rows.map(row => <div key={row.date} title={`${row.date} · ${row.pv} PV`}><i style={{ height: `${Math.max(4, Number(row.pv) / max * 100)}%` }} /><span>{row.date.slice(5)}</span></div>)}</div> : <p className="admin-empty">暂无真实访问记录</p>}</section>; }
export default function AdminDashboard({ initial }: { initial: Data }) { const [data, setData] = useState(initial); const [loading, setLoading] = useState(false); const change = async (range: string) => { setLoading(true); try { const response = await fetch(`/api/admin/overview?range=${range}`); if (response.ok) setData(await response.json()); } finally { setLoading(false); } }; return <main className="admin-content dashboard-workspace"><header className="admin-head"><div><p>运营总览</p><h1>企业运营中心</h1><span>所有统计均来自网站已记录的访问和客户询盘。</span></div><div className="admin-ranges">{[['7d','近 7 天'],['30d','近 30 天'],['90d','近 90 天']].map(([key,label]) => <button className={data.range === Number(key.slice(0,-1)) ? 'active' : ''} disabled={loading} onClick={() => change(key)} key={key}>{label}</button>)}</div></header><section className="admin-metrics"><article><span>页面浏览</span><strong>{number(data.summary.pv)}</strong></article><article><span>独立访客</span><strong>{number(data.summary.visitors)}</strong></article><article><span>访问会话</span><strong>{number(data.summary.sessions)}</strong></article><article><span>客户询盘</span><strong>{number(data.summary.inquiries)}</strong></article></section><Trend rows={data.trend}/><div className="admin-grid"><Bars title="来源平台" rows={data.sources} href="/admin/analytics"/><Bars title="热门页面" rows={data.pages} href="/admin/analytics"/></div><section className="admin-panel admin-table"><div className="admin-panel-heading"><h2>最近客户询盘</h2><Link href="/admin/leads">查看全部</Link></div><table><thead><tr><th>客户</th><th>公司</th><th>国家</th><th>产品</th><th>来源</th><th>状态</th><th>时间</th></tr></thead><tbody>{data.recentLeads.length ? data.recentLeads.map(lead => <tr key={lead.id}><td><b>{lead.name || lead.email || '-'}</b></td><td>{lead.company || '-'}</td><td>{lead.country || '-'}</td><td>{lead.product || '-'}</td><td>{lead.source || '-'}</td><td><span className="admin-badge">{lead.status}</span></td><td>{new Date(lead.created_at).toLocaleDateString('zh-CN')}</td></tr>) : <tr><td colSpan={7}>暂无客户询盘</td></tr>}</tbody></table></section></main>; }
