'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import AdminDateRange, { rangeQuery, type RangeValue } from './AdminDateRange';

type Mode = 'leads' | 'customers' | 'followups';
type Lead = { id: string; name: string; company: string; email: string; country: string; product: string; source: string; status: string; score: number; created_at: string };
type Customer = { id: string; company: string; country: string; industry: string; level: string; updated_at: string };
type FollowUp = { id: string; title: string; priority: string; status: string; due_at: string | null; lead_name: string; customer_name: string };
type AnyRow = Lead | Customer | FollowUp;
type ListData = { rows: AnyRow[]; total: number; page: number; limit: number; summary: Record<string, number> };
const leadStatuses = [['', '全部状态'], ['new', '新询盘'], ['contacted', '已联系'], ['qualified', '已确认'], ['quoting', '报价中'], ['negotiating', '洽谈中'], ['won', '已成交'], ['lost', '已流失'], ['invalid', '无效']];
const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Shanghai' });
const initialRange = (): RangeValue => ({ key: 'month', from: today(), to: today(), label: '本月' });
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }) : '未设置';
const Badge = ({children,tone}:{children:React.ReactNode;tone?:string}) => <span className={`admin-badge ${tone || ''}`}>{children}</span>;

export default function CrmWorkspace({ mode }: { mode: Mode }) {
  const [data,setData]=useState<ListData|null>(null);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[showCreate,setShowCreate]=useState(false);
  const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[range,setRange]=useState<RangeValue>(initialRange),[page,setPage]=useState(1),[error,setError]=useState('');
  const endpoint=mode==='leads'?'/api/leads':mode==='customers'?'/api/customers':'/api/follow-ups';
  const title=mode==='leads'?'客户询盘':mode==='customers'?'客户':'跟进任务';
  const subtitle=mode==='leads'?'处理网站提交与人工录入的客户询盘。':mode==='customers'?'维护客户资料与等级。':'安排和完成客户跟进。';
  const params=useCallback(()=>{const p=new URLSearchParams(rangeQuery(range));p.set('page',String(page));if(query&&mode!=='followups')p.set('q',query);if(status&&mode!=='customers')p.set('status',status);return p.toString()},[mode,range,page,query,status]);
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError('');try{const response=await fetch(`${endpoint}?${params()}`,{cache:'no-store',signal});if(!response.ok)throw Error('读取数据失败');setData(await response.json() as ListData)}catch(e){if(e instanceof Error&&e.name==='AbortError')return;setError('读取数据失败')}finally{if(!signal?.aborted)setLoading(false)}},[endpoint,params]);
  useEffect(()=>{const p=new URLSearchParams(location.search);const q=p.get('q');if(q&&mode==='leads')setQuery(q);const key=p.get('range');if(key&&['today','week','month','90d','custom'].includes(key)){const from=p.get('from')||today(),to=p.get('to')||today();if(key!=='custom'||(/^\d{4}-\d{2}-\d{2}$/.test(from)&&/^\d{4}-\d{2}-\d{2}$/.test(to)&&from<=to&&to<=today()))setRange({key:key as RangeValue['key'],from,to,label:({today:'今天',week:'本周',month:'本月','90d':'近 90 天',custom:from+' 至 '+to} as Record<string,string>)[key]})}},[mode]);
  useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>load(controller.signal),query?260:0);return()=>{clearTimeout(timer);controller.abort()}},[load,query]);
  const changeRange=(value:RangeValue)=>{setRange(value);setPage(1)};
  const update=async(id:string,body:object)=>{setSaving(true);setError('');try{const response=await fetch(`${endpoint}/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw Error();await load()}catch{setError('保存失败，请重试')}finally{setSaving(false)}};
  const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError('');const form=new FormData(event.currentTarget);const body=Object.fromEntries(form.entries());try{if(mode==='followups'&&body.dueAt)body.dueAt=new Date(String(body.dueAt)).toISOString();const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw Error();setShowCreate(false);setPage(1);await load()}catch{setError('创建失败，请检查输入内容')}finally{setSaving(false)}};
  const count=data?.summary||{};
  const summary=mode==='leads'?[['总询盘',count.total],['待处理',count.pending],['高潜力',count.high]]:mode==='customers'?[['客户总数',count.total],['A 级客户',count.a],['B 级客户',count.b]]:[['任务总数',count.total],['待办任务',count.pending],['已完成',count.completed]];
  const totalPages=Math.max(1,Math.ceil((data?.total||0)/(data?.limit||20)));
  return <main className="admin-content crm-workspace">
    <header className="crm-header"><div><p>销售工作台</p><h1>{title}</h1><span>{subtitle}</span></div><button className="admin-primary" onClick={()=>setShowCreate(true)}>+ {mode==='leads'?'新建询盘':mode==='customers'?'新建客户':'新建任务'}</button></header>
    <AdminDateRange value={range} onChange={changeRange} busy={loading}/>
    <section className="crm-summary" aria-label={`${range.label}摘要`}>{summary.map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{value===undefined?'—':Number(value).toLocaleString('zh-CN')}</strong></article>)}</section>
    <section className="admin-panel crm-list"><div className="crm-tools">
      {mode!=='followups'?<input aria-label={mode==='leads'?'搜索姓名、公司或邮箱':'搜索公司或国家'} value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder={mode==='leads'?'搜索姓名、公司或邮箱':'搜索公司或国家'}/>:null}
      {mode==='leads'?<select aria-label="询盘状态" value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}>{leadStatuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:mode==='followups'?<select aria-label="任务状态" value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="">全部任务</option><option value="pending">待办</option><option value="completed">已完成</option><option value="cancelled">已取消</option></select>:null}
      <button className="admin-secondary" onClick={()=>load()} disabled={loading}>刷新</button>
    </div>
    {error?<p className="admin-error" role="alert">{error}</p>:null}
    <div className="admin-table"><table>{mode==='leads'?<LeadTable rows={(data?.rows||[]) as Lead[]} update={update} saving={saving}/>:mode==='customers'?<CustomerTable rows={(data?.rows||[]) as Customer[]} update={update} saving={saving}/>:<FollowTable rows={(data?.rows||[]) as FollowUp[]} update={update} saving={saving}/>}</table></div>
    {loading?<p className="admin-empty" role="status">正在读取数据…</p>:!data?.rows.length?<p className="admin-empty">当前范围暂无记录</p>:null}
    {data&&data.total>0?<div className="admin-pagination"><span>第 {data.page} / {totalPages} 页 · 共 {data.total.toLocaleString('zh-CN')} 条</span><div><button type="button" className="admin-secondary" disabled={loading||page<=1} onClick={()=>setPage(page-1)}>上一页</button><button type="button" className="admin-secondary" disabled={loading||page>=totalPages} onClick={()=>setPage(page+1)}>下一页</button></div></div>:null}
    </section>
    {showCreate?<div className="admin-modal-backdrop" role="presentation"><form className="admin-modal" onSubmit={create}><button type="button" className="admin-modal-close" onClick={()=>setShowCreate(false)} aria-label="关闭">×</button><p>销售工作台</p><h2>{mode==='leads'?'新建客户询盘':mode==='customers'?'新建客户':'安排跟进任务'}</h2>{mode==='leads'?<><label>姓名<input name="name"/></label><label>公司<input name="company"/></label><label>邮箱<input required type="email" name="email"/></label><label>国家/地区<input name="country"/></label><label>关注产品<input name="product"/></label><label>客户需求<textarea name="message" rows={3}/></label></>:mode==='customers'?<><label>公司名称<input required name="company"/></label><label>国家/地区<input name="country"/></label><label>行业<input name="industry"/></label><label>客户等级<select name="level"><option value="C">C 级</option><option value="B">B 级</option><option value="A">A 级</option><option value="D">D 级</option></select></label></>:<><label>任务名称<input required name="title"/></label><label>截止时间<input name="dueAt" type="datetime-local"/></label><label>优先级<select name="priority"><option value="normal">普通</option><option value="high">高</option><option value="urgent">紧急</option><option value="low">低</option></select></label></>}<footer><button type="button" className="admin-secondary" onClick={()=>setShowCreate(false)}>取消</button><button className="admin-primary" disabled={saving}>{saving?'保存中…':'保存'}</button></footer></form></div>:null}
  </main>;
}

function LeadTable({rows,update,saving}:{rows:Lead[];update:(id:string,body:object)=>void;saving:boolean}){return <><thead><tr><th>客户</th><th>公司 / 国家</th><th>关注产品</th><th>来源</th><th>评分</th><th>状态</th><th>收到时间</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.name||'未填写姓名'}</b><small>{row.email||'—'}</small></td><td>{row.company||'—'}<small>{row.country||'—'}</small></td><td>{row.product||'—'}</td><td>{row.source||'—'}</td><td><Badge tone={row.score>=70?'good':''}>{row.score}</Badge></td><td><select aria-label="更新询盘状态" value={row.status} disabled={saving} onChange={event=>update(row.id,{status:event.target.value})}>{leadStatuses.slice(1).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></td><td>{formatDate(row.created_at)}</td></tr>)}</tbody></>}
function CustomerTable({rows,update,saving}:{rows:Customer[];update:(id:string,body:object)=>void;saving:boolean}){return <><thead><tr><th>公司</th><th>国家/地区</th><th>行业</th><th>客户等级</th><th>最近更新</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.company}</b></td><td>{row.country||'—'}</td><td>{row.industry||'—'}</td><td><select aria-label="更新客户等级" value={row.level} disabled={saving} onChange={event=>update(row.id,{level:event.target.value})}>{['A','B','C','D'].map(level=><option key={level} value={level}>{level} 级</option>)}</select></td><td>{formatDate(row.updated_at)}</td></tr>)}</tbody></>}
function FollowTable({rows,update,saving}:{rows:FollowUp[];update:(id:string,body:object)=>void;saving:boolean}){return <><thead><tr><th>任务</th><th>关联对象</th><th>优先级</th><th>截止时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><b>{row.title}</b></td><td>{row.lead_name||row.customer_name||'—'}</td><td><Badge tone={['high','urgent'].includes(row.priority)?'warn':''}>{({low:'低',normal:'普通',high:'高',urgent:'紧急'} as Record<string,string>)[row.priority]||row.priority}</Badge></td><td>{formatDate(row.due_at)}</td><td><Badge tone={row.status==='completed'?'good':''}>{({pending:'待办',completed:'已完成',cancelled:'已取消'} as Record<string,string>)[row.status]||row.status}</Badge></td><td>{row.status==='pending'?<button className="admin-text-button" disabled={saving} onClick={()=>update(row.id,{status:'completed'})}>标记完成</button>:null}</td></tr>)}</tbody></>}
