'use client';
import { FormEvent, useEffect, useState } from 'react';

type Kind = 'products' | 'content' | 'forms';
type Item = { id:string; name?:string; title?:string; slug?:string; sku?:string; type?:string; status?:string; active?:boolean };
const details = { products:['产品管理','维护产品目录、发布状态和产品标识。','新建产品'], content:['内容管理','管理文章、案例、应用内容与下载资料。','新建内容'], forms:['网站表单','配置各业务场景的客户信息收集表单。','新建表单'] } as const;
const slugify = (value:string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

function DataRows({ kind, items }: { kind:Kind; items:Item[] }) {
  return <>{items.map(item => <tr key={item.id}>{kind === 'products' ? <><td><b>{item.name}</b></td><td>{item.sku || '-'}</td><td>{item.slug}</td><td><span className="admin-badge">{item.status === 'published' ? '已发布' : item.status === 'archived' ? '已归档' : '草稿'}</span></td></> : kind === 'content' ? <><td>{item.type}</td><td><b>{item.title}</b></td><td>{item.slug}</td><td><span className="admin-badge">{item.status === 'published' ? '已发布' : item.status === 'archived' ? '已归档' : '草稿'}</span></td></> : <><td><b>{item.name}</b></td><td>{item.type}</td><td><span className={`admin-badge ${item.active ? 'good' : ''}`}>{item.active ? '启用' : '停用'}</span></td></>}</tr>)}</>;
}

export default function OperationsWorkspace({ kind }: { kind:Kind }) {
  const [items, setItems] = useState<Item[]>([]); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [title, intro, create] = details[kind];
  const load = async () => { setError(''); try { const response = await fetch(`/api/${kind}`); if (!response.ok) throw new Error(); setItems(await response.json()); } catch { setError('无法读取数据'); } };
  useEffect(() => { load(); }, []);
  const submit = async (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); const data:Record<string,unknown> = Object.fromEntries(new FormData(event.currentTarget)); if (kind !== 'forms' && !data.slug) data.slug = slugify(String(data.name || data.title || '')); if (kind === 'forms') data.active = true; try { const response = await fetch(`/api/${kind}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data) }); if (!response.ok) throw new Error(); setOpen(false); await load(); } catch { setError('保存失败，请检查名称和 URL 标识是否重复。'); } finally { setSaving(false); } };
  return <main className="admin-content crm-workspace"><header className="crm-header"><div><p>网站运营</p><h1>{title}</h1><span>{intro}</span></div><button className="admin-primary" onClick={() => setOpen(true)}>+ {create}</button></header><section className="admin-panel crm-list"><div className="crm-tools"><span>当前记录 {items.length}</span><button className="admin-secondary" onClick={load}>刷新</button></div>{error ? <p className="admin-error">{error}</p> : null}<div className="admin-table"><table><thead><tr>{kind === 'products' ? <><th>产品名称</th><th>SKU</th><th>URL 标识</th><th>状态</th></> : kind === 'content' ? <><th>类型</th><th>标题</th><th>URL 标识</th><th>状态</th></> : <><th>表单名称</th><th>业务场景</th><th>状态</th></>}</tr></thead><tbody><DataRows kind={kind} items={items}/>{!items.length ? <tr><td colSpan={4}>暂无记录</td></tr> : null}</tbody></table></div></section>{open ? <div className="admin-modal-backdrop"><form className="admin-modal" onSubmit={submit}><button type="button" className="admin-modal-close" onClick={() => setOpen(false)}>×</button><p>网站运营</p><h2>{create}</h2>{kind === 'products' ? <><label>产品名称<input required name="name"/></label><label>URL 标识<input name="slug" placeholder="例如: portable-office"/></label><label>SKU<input name="sku"/></label><label>发布状态<select name="status"><option value="draft">草稿</option><option value="published">发布</option><option value="archived">归档</option></select></label></> : kind === 'content' ? <><label>内容类型<select name="type"><option value="blog">文章</option><option value="case-study">案例</option><option value="application">应用</option><option value="faq">常见问题</option><option value="download">下载资料</option></select></label><label>标题<input required name="title"/></label><label>URL 标识<input name="slug"/></label><label>正文<textarea name="content" rows={6}/></label><label>发布状态<select name="status"><option value="draft">草稿</option><option value="published">发布</option><option value="archived">归档</option></select></label></> : <><label>表单名称<input required name="name"/></label><label>业务场景<select name="type"><option value="general">通用咨询</option><option value="product">产品咨询</option><option value="oem-odm">OEM/ODM</option><option value="quote">询价</option><option value="sample">样品</option><option value="contact">联系我们</option></select></label></>}<footer><button className="admin-secondary" type="button" onClick={() => setOpen(false)}>取消</button><button className="admin-primary" disabled={saving}>{saving ? '保存中…' : '保存'}</button></footer></form></div> : null}</main>;
}
