export const storeConfig = {
  storeName: "COWINLIFE",
  legalCompanyName: "Quzhou Qiying Import & Export Co., Ltd.",
  domain: "cowinlife.com",
  brandSlogan: "Peel, place, and make the room feel new.",
  brandDescription:
    "COWINLIFE creates removable wall decals, window films, and peel-and-stick surfaces for nursery rooms, playrooms, cozy apartments, and quick home refresh projects.",
  industry: "Home decor and DIY surface decoration",
  headquartersCountry: "China",
  address: "Room 110, 1st Floor, Building 2, Qushidai Future Building, Kecheng District, Quzhou City, Zhejiang Province, China",
  supportEmail: "qianxinyue@cowinlife.com",
  inquiryEmail: "davidsha@cowinlife.com",
  supportPhone: "+86 131 5707 3736",
  whatsapp: "+8613157073736",
  whatsappChatUrl: "https://wa.me/message/4W2MTNLSRDN6I1",
  businessHours: "Mon-Fri, 9:00-17:00 China Standard Time",
  defaultLocale: "en",
  supportedLocales: ["en"],
  defaultCurrency: "USD",
  supportedCurrencies: ["USD", "EUR", "GBP", "CAD", "AUD", "JPY", "CNY"],
  primaryColor: "#263238",
  secondaryColor: "#d66b4d",
  accentColor: "#f6c65b",
  freeShippingThreshold: 49,
  defaultCountry: "US",
  socialLinks: {
    instagram: "",
    tiktok: "",
    youtube: "",
    facebook: "",
    pinterest: "",
    x: ""
  },
  payments: ["Card via hosted payment element", "PayPal", "Gift card balance"],
  returnsWindowDays: 30,
  cookieMode: "analytics opt-in",
  launchOfferCode: "WELCOME15"
};
