import { NextResponse } from 'next/server';
import { z } from 'zod';
import { log, requirePermission } from '@/lib/admin-api';
import { query } from '@/lib/database';
import { revalidatePath } from 'next/cache';
const input=z.object({path:z.string().min(1).max(240),title:z.string().max(180).optional(),description:z.string().max(500).optional(),canonical:z.string().url().optional().or(z.literal('')),schema:z.record(z.string(),z.unknown()).default({})});
export const runtime='nodejs';
export async function GET(request:Request){const b=await requirePermission('growth');if(b)return b;const params=new URL(request.url).searchParams;const page=Math.max(1,Math.floor(Number(params.get('page'))||1));const limit=20;const search=(params.get('q')||'').trim().slice(0,120);const values=search?[`%${search}%`]:[];const where=search?'WHERE path ILIKE $1 OR title ILIKE $1':'';const [rows,count]=await Promise.all([query(`SELECT id,path,title,canonical,updated_at FROM seo_pages ${where} ORDER BY updated_at DESC LIMIT ${limit} OFFSET ${(page-1)*limit}`,values),query<{count:string}>(`SELECT count(*)::text count FROM seo_pages ${where}`,values)]);return NextResponse.json({rows:rows.rows,total:Number(count.rows[0]?.count||0),page,limit},{headers:{'Cache-Control':'private, no-store'}})}
export async function POST(request:Request){const b=await requirePermission('growth');if(b)return b;const p=input.safeParse(await request.json());if(!p.success)return NextResponse.json({error:'Invalid SEO page'},{status:400});const d=p.data;const r=await query<{id:string}>('INSERT INTO seo_pages(path,title,description,canonical,schema) VALUES($1,$2,$3,$4,$5) ON CONFLICT(path) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,canonical=EXCLUDED.canonical,schema=EXCLUDED.schema,updated_at=now() RETURNING id',[d.path,d.title||'',d.description||'',d.canonical||'',JSON.stringify(d.schema)]);await log('saved','seo',r.rows[0].id);revalidatePath(d.path);return NextResponse.json(r.rows[0])}
