import { NextResponse } from 'next/server';
import { z } from 'zod';
import { log, requireAdmin } from '@/lib/admin-api';
import { query } from '@/lib/database';
import { rangeFromRequest } from '@/lib/admin-date-range';
const input=z.object({leadId:z.string().uuid().optional(),customerId:z.string().uuid().optional(),title:z.string().min(1).max(200),dueAt:z.string().datetime().optional(),priority:z.enum(['low','normal','high','urgent']).default('normal')});
export const runtime='nodejs';
export async function GET(request:Request){const blocked=await requireAdmin();if(blocked)return blocked;let range;try{range=rangeFromRequest(request)}catch{return NextResponse.json({error:'Invalid date range'},{status:400})}const url=new URL(request.url);const page=Math.max(1,Math.floor(Number(url.searchParams.get('page'))||1)),limit=20;const status=url.searchParams.get('status')||'';const values:unknown[]=[range.start,range.end];let where='f.created_at >= $1 AND f.created_at < $2';if(['pending','completed','cancelled'].includes(status)){values.push(status);where+=` AND f.status=$${values.length}`;}const [rows,counts]=await Promise.all([query(`SELECT f.id,f.title,f.priority,f.status,f.due_at,coalesce(l.name,l.email,'') lead_name,coalesce(c.company,'') customer_name FROM follow_ups f LEFT JOIN leads l ON l.id=f.lead_id LEFT JOIN customers c ON c.id=f.customer_id WHERE ${where} ORDER BY f.due_at ASC NULLS LAST,f.created_at DESC LIMIT ${limit} OFFSET ${(page-1)*limit}`,values),query<{total:string;pending:string;high:string;completed:string}>(`SELECT count(*)::text total,count(*) FILTER(WHERE f.status='pending')::text pending,count(*) FILTER(WHERE f.priority IN ('high','urgent'))::text high,count(*) FILTER(WHERE f.status='completed')::text completed FROM follow_ups f WHERE ${where}`,values)]);const c=counts.rows[0];return NextResponse.json({rows:rows.rows,total:Number(c?.total||0),page,limit,summary:{total:Number(c?.total||0),pending:Number(c?.pending||0),high:Number(c?.high||0),completed:Number(c?.completed||0)}},{headers:{'Cache-Control':'private, no-store'}})}
export async function POST(request:Request){const blocked=await requireAdmin();if(blocked)return blocked;const parsed=input.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'Invalid follow-up'},{status:400});const d=parsed.data;const r=await query<{id:string}>('INSERT INTO follow_ups (lead_id,customer_id,title,due_at,priority) VALUES ($1,$2,$3,$4,$5) RETURNING id',[d.leadId||null,d.customerId||null,d.title,d.dueAt||null,d.priority]);await log('created','follow-up',r.rows[0].id);return NextResponse.json(r.rows[0],{status:201});}
